### ISSUE TITLE
lein-sub broken on lein 2

### ISSUE THREAD

**Issue by mobileink** [kumarshantanu/lein-sub#10]
This is broken:

lein-sub/src/leiningen/sub.clj:

```
                   (project/read (str sub-proj-dir "/project.clj")))
```

leiningen/leiningen-core/src/leiningen/core/project.clj/read:

(defn read
  "Read project map out of file, which defaults to project.clj."
  ([file profiles]...

**Comment by kumarshantanu** [comment]
Can you propose what should be the correct behavior?

**Comment by kumarshantanu** [comment]
The function `leiningen.core.project/read` supports multiple arities, hence this is not a problem. Feel free to reopen if I missed the point.
