### ISSUE TITLE
lein sub fails when working with lein reagent template generated projects

### ISSUE THREAD

**Issue by publicmayhem** [kumarshantanu/lein-sub#13]
I have been using lein sub for a while now and it has has been a godsend! 

However, when I added a sub project created using the reagent template, sub install starts to fail over

To replicate try the following

> lein new parent
> cd parent
> lein new reagent child
> *\* edit parent/project.clj to add lein-sub plugin and sub directory as
> :plugins [[lein-sub "0.3.0"]]
> :sub ["child"]
> so my parent/project.clj looks like
> (defproject parent "0.1.0-SNAPSHOT"
>   :description "FIXME: write description"
>   :url "http://example.com/FIXME"
>   :license {:name "Eclipse Public License"
>             :url "http://www.eclipse.org/legal/epl-v10.html"}
>   :plugins [[lein-sub "0.3.0"]]
>   :sub ["child"]
>   :dependencies [[org.clojure/clojure "1.7.0"]])

then

> lein sub install
> ......... output
> lein sub install
> Reading project from child

minifying assets...
java.io.FileNotFoundException: resources/public/css/site.css (No such file or directory)
 at java.io.FileInputStream.open (FileInputStream.java:-2)
....

How can I get sub to work with reagent template projects?

Thx for any help,
Rob

**Comment by kumarshantanu** [comment]
I can't say for sure what's going on but here's my guess: [lein-assets-minifier](https://github.com/yogthos/lein-asset-minifier) accepts relative file paths as argument (assumes current directory to be the project directory), whereas when using _lein-sub_ the current directory is still the parent directory. The expectation breaks, and hence the error that you see. Sadly, Java does not allow to change the current directory.

/cc @yogthos

**Comment by publicmayhem** [comment]
Thanks for looking kumarshantanu. Following your clue, I am raising a pull request on [lein-asset-minifier](https://github.com/yogthos/lein-asset-minifier) to pull in (:root project) when the file path is relative to fix my issue. This will then work with lein-sub.

Rob
